<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 *
 * @author Yaro (https://yaro.info) glodov@gmail.com
 */
return [
    'Space has been archived' => 'Спільнота запакована',
    'Space has been unarchived' => 'Спільнота розпакована',
    'Space member joined' => 'Доєднався член спільноти',
    'Space member left' => 'Член вийшов із спільноти',
    'Whenever a member leaves one of your spaces.' => 'Коли член виходить із спільноти.',
    'Whenever a new member joined one of your spaces.' => 'Коли новий член доєднується до одної із спільнот.',
    'Whenever a space is archived.' => 'Коли спільнота запакована.',
    'Whenever a space is unarchived.' => 'Коли спільнота розпакована.',
];
